/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/elenco-movimenti-conto-corrente": {
    /** L’operazione consente di ottenere un elenco di movimenti per il conto corrente passato. */
    post: operations["recuperaMovimentiContoCorrente"];
  };
}

export interface definitions {
  RecuperaMovimentiRequest: {
    tracciaturaApplicativa: definitions["TracciaturaApplicativa"];
    contoCorrente?: definitions["ContoCorrente"];
    filtriDiRicerca?: definitions["FiltriDiRicerca"];
  };
  TracciaturaApplicativa: {
    codiceApplicazioneChiamante: definitions["CodiceApplicazione"];
    versioneApplicazioneChiamante?: definitions["VersioneApplicazione"];
    /** idCorrelazione (medesimo di quanto in testata) */
    idCorrelazione: string;
    /** Identificativo postazione banca (ComputerName) o del server di provenienza della chiamata nel caso di invocazione da canali diretti (ad esempio internet banking). */
    identificativoHostFisicoChiamante: string;
    /** Identificativo del terminale posto di lavoro */
    identificativoTerminaleChiamante: string;
    /** Matricola operatore/gestore o identificativo univoco dell’utente che ha avviato la pratica */
    identificativoUtenteChiamante: string;
    /** identificativoFilialeChiamante */
    identificativoFilialeChiamante: string;
    /** identificativoCassaChiamante */
    identificativoCassaChiamante?: string;
  };
  FiltriDiRicerca: {
    intervalloTemporale?: definitions["IntervalloTemporale"];
    codiceCausale?: definitions["CodiceCausale"];
    importoMovimento?: definitions["Importo"];
    /** Data valuta del movimento */
    dataValuta?: string;
  };
  /** Inizio e fine dell’intervallo di ricerca movimenti */
  IntervalloTemporale: {
    /** Inizio dell’intervallo di ricerca. Non può essere più vecchia di due anni. Filtro di ricerca obbligatorio */
    dataInizio?: string;
    /** Fine dell’intervallo di ricerca. Non può essere antecedente alla data Inizio e non può essere  Filtro di ricerca obbligatorio */
    dataFine?: string;
  };
  Error: {
    /** Codice dell'errore */
    codice: string;
    /** Messaggio dell'errore */
    messaggio: string;
    /** Layer dell'errore */
    layer: string;
  };
  ElencoMovimenti: {
    contoCorrente?: definitions["ContoCorrente"];
    dataFineEstrazione?: string;
    ndg?: string;
    anagraficaNdg?: string;
    descFilialeOperante?: string;
    descFilialeCedente?: string;
    socioBanca?: boolean;
    saldoContabile?: string;
    /** Lista movimenti */
    movimentiContoCorrente?: definitions["MovimentiContoCorrente"][];
  };
  MovimentiContoCorrente: {
    identificativoMovimentoPerContoCorrente?: string;
    dateMovimento?: definitions["DateMovimento"];
    /** Data ora del movimento */
    dataOraRegistrazione: string;
    /** Data disponibilità */
    dataDisponibilita: string;
    importo: definitions["Importo"];
    causale?: definitions["Causale"];
    codiceUnitaOperativaGenerante?: string;
    codiceEnteCassa?: string;
    descrizioneMovimento: string;
    codiceBelfiore?: string;
  };
  ContoCorrente: {
    codiceFiliale: definitions["CodiceFiliale"];
    categoria: definitions["CategoriaRapporto"];
    numero: definitions["NumeroRapporto"];
  };
  /** Date del movimento */
  DateMovimento: {
    /** Data valuta del movimento */
    dataValuta: string;
    /** Data contabile del movimento */
    dataContabile: string;
  };
  /** Codice a 5 identificativo dell’applicazione chiamante */
  CodiceApplicazione: string;
  /** Versione del software chiamante */
  VersioneApplicazione: string;
  /** Identificativo del terminale posto di lavoro */
  CodiceCausale: string;
  /** Identificativo della filiale del rapporto */
  CodiceFiliale: string;
  /** Identificativo della categoria del rapporto */
  CategoriaRapporto: string;
  /** Identificativo del numero del rapporto */
  NumeroRapporto: string;
  /** Causale del movimento */
  Causale: {
    /** Codice causale Es. Codice: ZI0 descrizione: BONIFICO DALL’ESTERO (ma su IB ESTERO-BONIFICO IN ENTRATA ) codice: 195 descr. IMPOSTA DI BOLLO E/C   (ma su IB viene mostrato “Imposta di bollo CC e LR”) */
    codice: string;
    /** Descrizione della causale (recuperato da tabella di arrichimento) */
    descrizione: string;
  };
  Importo: string;
}

export interface parameters {
  /** Codice che identifica univocamente l'applicazione diretta chiamante. Sono ammesse stringhe non vuote (es. APSD2, YOUWEB, HD005 ...) */
  "Bbpm-Tt-IdOperazione-CodiceApplicazioneChiamante": string;
  /** Codice univoco dell'operazione generata dall'applicativo chiamante. L'applicativo chiamante deve garantire l'univocità di questo codice all'interno del suo perimetro. È obbligatorio solo nelle operazione di non lettura */
  "Bbpm-Tt-IdOperazione-CodiceOperazione": string;
  /** Codice univoco per la tracciatura su tutta la filiera delle chiamate (end to end). */
  "Bbpm-Tt-IdCorrelazione": string;
  /** Codice dell'istituto target del servizio. Sono ammesse stringhe numeriche composte esattamente da 5 caratteri (es. 05034, 03045, 03102 ...) */
  "Bbpm-Tc-CodiceABI": string;
  /** Codice del canale di origine della chiamata */
  "Bbpm-Tc-CodiceCanale":
    | "SITO_PUBBLICO"
    | "CORPORATE_BANKING"
    | "INTERNET_BANKING"
    | "PSD2"
    | "FILIALE_CORPORATE"
    | "AGENZIA_RETAIL"
    | "UFFICI"
    | "MOBILE_PRIVATI"
    | "MOBILE_CORPORATE";
  /** Codice che identifica univocamente l'applicazione chiamante di canale dalla quale è partita la chiamata (FACEBOOK, APP, YOUWEB, NSR ...) */
  "Bbpm-Tc-CodiceApplicazioneChiamante": string;
  /** Codice ndg del cliente che sta effetutando l'operazione. Sono ammesse stringhe numeriche con lunghezza minima 1 e massima 12 (es. 000007865 ...) */
  "Bbpm-Tc-Cliente-CodiceNdg": string;
  /** Identificativo dell'utente privato. Sono ammesse stringhe non vuote */
  "Bbpm-Tc-Cliente-CodiceUtenzaIb-Identificativo-Utente": string;
  /** Identificativo postazione dell'utente corporate. Sono ammesse stringhe non vuote */
  "Bbpm-Tc-Cliente-CodiceUtenzaCb-Identificativo-Postazione": string;
  /** Identificativo dell'utente corporate. Sono ammesse stringhe non vuote */
  "Bbpm-Tc-Cliente-CodiceUtenzaCb-Identificativo-Utente": string;
  /** Matricola dell'utente interno. Sono ammesse stringhe non vuote */
  "Bbpm-Tc-UtenzaInterna-Matricola": string;
  /** Codice dell'ufficio dell'utente interno. Sono ammesse stringhe non vuote */
  "Bbpm-Tc-UtenzaInterna-CodiceUnitaOrganizzativa": string;
  /** Identificativo di un eventuale entità esterna alla banca (es. PSD2, partner commerciale) che consuma servizi esposti dalla banca. Più precisamente è valorizzato con il nome o il codice della controparte (es. Facebook Inc). Sono ammesse stringhe non vuote */
  "Bbpm-Tc-Controparte-IdControparte": string;
}

export interface responses {
  /** Lista delle pratiche recuperate dal sistema secondo i filtri specificati */
  ElencoMovimentiRecuperatoConSuccesso: {
    headers: {};
    schema: definitions["ElencoMovimenti"];
  };
  /** Errore applicativo, ad esempio richiesta non valida */
  Error400: {
    headers: {};
    schema: definitions["Error"];
  };
  /** Errore applicativo, cliente non trovato */
  Error404: {
    headers: {};
    schema: definitions["Error"];
  };
  /** Errore sistemistico e/o errore generico */
  Error500: {
    headers: {};
    schema: definitions["Error"];
  };
  /** Errore di timeout */
  Error504: {
    headers: {};
    schema: definitions["Error"];
  };
}

export interface operations {
  /** L’operazione consente di ottenere un elenco di movimenti per il conto corrente passato. */
  recuperaMovimentiContoCorrente: {
    parameters: {
      header: {
        /** Codice che identifica univocamente l'applicazione diretta chiamante. Sono ammesse stringhe non vuote (es. APSD2, YOUWEB, HD005 ...) */
        "Bbpm-Tt-IdOperazione-CodiceApplicazioneChiamante": parameters["Bbpm-Tt-IdOperazione-CodiceApplicazioneChiamante"];
        /** Codice univoco dell'operazione generata dall'applicativo chiamante. L'applicativo chiamante deve garantire l'univocità di questo codice all'interno del suo perimetro. È obbligatorio solo nelle operazioni di non lettura */
        "Bbpm-Tt-IdOperazione-CodiceOperazione": string;
        /** Codice univoco per la tracciatura su tutta la filiera delle chiamate (end to end). */
        "Bbpm-Tt-IdCorrelazione": parameters["Bbpm-Tt-IdCorrelazione"];
        /** Codice dell'istituto target del servizio. Sono ammesse stringhe numeriche composte esattamente da 5 caratteri (es. 05034, 03045, 03102 ...) */
        "Bbpm-Tc-CodiceABI": parameters["Bbpm-Tc-CodiceABI"];
        /** Codice del canale di origine della chiamata */
        "Bbpm-Tc-CodiceCanale": parameters["Bbpm-Tc-CodiceCanale"];
        /** Codice che identifica univocamente l'applicazione chiamante di canale dalla quale è partita la chiamata (FACEBOOK, APP, YOUWEB, NSR ...) */
        "Bbpm-Tc-CodiceApplicazioneChiamante": parameters["Bbpm-Tc-CodiceApplicazioneChiamante"];
        /** Codice ndg del cliente che sta effetutando l'operazione. Sono ammesse stringhe numeriche con lunghezza minima 1 e massima 12 (es. 000007865 ...) */
        "Bbpm-Tc-Cliente-CodiceNdg"?: parameters["Bbpm-Tc-Cliente-CodiceNdg"];
        /** Identificativo dell'utente privato. Sono ammesse stringhe non vuote */
        "Bbpm-Tc-Cliente-CodiceUtenzaIb-Identificativo-Utente"?: parameters["Bbpm-Tc-Cliente-CodiceUtenzaIb-Identificativo-Utente"];
        /** Identificativo postazione dell'utente corporate. Sono ammesse stringhe non vuote */
        "Bbpm-Tc-Cliente-CodiceUtenzaCb-Identificativo-Postazione"?: parameters["Bbpm-Tc-Cliente-CodiceUtenzaCb-Identificativo-Postazione"];
        /** Identificativo dell'utente corporate. Sono ammesse stringhe non vuote */
        "Bbpm-Tc-Cliente-CodiceUtenzaCb-Identificativo-Utente"?: parameters["Bbpm-Tc-Cliente-CodiceUtenzaCb-Identificativo-Utente"];
        /** Matricola dell'utente interno. Sono ammesse stringhe non vuote */
        "Bbpm-Tc-UtenzaInterna-Matricola"?: parameters["Bbpm-Tc-UtenzaInterna-Matricola"];
        /** Codice dell'ufficio dell'utente interno. Sono ammesse stringhe non vuote */
        "Bbpm-Tc-UtenzaInterna-CodiceUnitaOrganizzativa"?: parameters["Bbpm-Tc-UtenzaInterna-CodiceUnitaOrganizzativa"];
        /** Identificativo di un eventuale entità esterna alla banca (es. PSD2, partner commerciale) che consuma servizi esposti dalla banca. Più precisamente è valorizzato con il nome o il codice della controparte (es. Facebook Inc). Sono ammesse stringhe non vuote */
        "Bbpm-Tc-Controparte-IdControparte"?: parameters["Bbpm-Tc-Controparte-IdControparte"];
      };
      body: {
        /** parametri per l'interrogazione dei movimenti di conto corrente */
        recuperaMovimentiRequest: definitions["RecuperaMovimentiRequest"];
      };
    };
    responses: {
      200: responses["ElencoMovimentiRecuperatoConSuccesso"];
      400: responses["Error400"];
      500: responses["Error500"];
      504: responses["Error504"];
    };
  };
}
